// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9wViXZQYNHO-LJrt-4Fran8flmtlMvuQ',
    appId: '1:546890337826:web:9d8309d8b828e98857c47b',
    messagingSenderId: '546890337826',
    projectId: 'nostracode-002',
    authDomain: 'nostracode-002.firebaseapp.com',
    storageBucket: 'nostracode-002.appspot.com',
    measurementId: 'G-L1R0N8V2KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78rcmvSE4HmZoBX6Kydf8WCmYhLDh92k',
    appId: '1:546890337826:android:ef528912d84103ea57c47b',
    messagingSenderId: '546890337826',
    projectId: 'nostracode-002',
    storageBucket: 'nostracode-002.appspot.com',
  );
}
